# Modélisation

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("clean_dataset.csv", index_col=0)

In [3]:
df

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,distance
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,205.527899
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,203.952229
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,205.244676
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,206.075218
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,206.075218
...,...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,266.229776
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,271.008439
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,265.183978
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,268.667236
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,259.752060

## Transformation des variables catégorielles en variables numériques

In [4]:
# Créer une liste contenant toutes les variables catégorielles

list_cat = [i for i in df.columns if df.dtypes[i]=="object"]
list_cat

['ocean_proximity']

In [5]:
# Encodage a chaud (one-hot encoding)
df_dumies = pd.get_dummies(df, columns=list_cat, prefix="Column", dtype=float)
df_dumies

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distance,Column_<1H OCEAN,Column_INLAND,Column_ISLAND,Column_NEAR BAY,Column_NEAR OCEAN
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,205.527899,0.0,0.0,0.0,1.0,0.0
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,203.952229,0.0,0.0,0.0,1.0,0.0
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,205.244676,0.0,0.0,0.0,1.0,0.0
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,206.075218,0.0,0.0,0.0,1.0,0.0
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,206.075218,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,266.229776,0.0,1.0,0.0,0.0,0.0
20636,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,271.008439,0.0,1.0,0.0,0.0,0.0
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,265.183978,0.0,1.0,0.0,0.0,0.0
20638,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,268.667236,0.0,1.0,0.0,0.0,0.0
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,259.752060,0.0,1.0,0.0,0.0,0.0

## Séparation du jeu de données (jeux d'entraînement et jeu de test)

In [7]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df_dumies, test_size = 0.3, random_state = 88)

In [8]:
# Choix des variables cibles et predictives entrainement
Y_train = train_set["median_house_value"]
X_train = train_set.drop(["median_house_value"], axis=1)

In [9]:
# Choix des variables cibles et predictives test
Y_test = test_set["median_house_value"]
X_test = test_set.drop(["median_house_value"], axis=1)

## Normalisation des variables ou mise a l'échelle

In [10]:
# Pour la normalisation plusieurs techniquaes sont employées : min-max scaler, standardscaler et robustscaler

from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
X_train_norm = scaler1.fit_transform(X_train)

In [11]:
scaler2 = StandardScaler()
X_test_norm = scaler2.fit_transform(X_test)

## Predictions

In [12]:
from lazypredict.Supervised import LazyRegressor
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, prediction = reg.fit(X_train_norm, X_test_norm, Y_train, Y_test)

 71%|███████▏  | 30/42 [01:13<00:20,  1.71s/it]